# -*- coding: utf-8 -*-
"""Personalized Finance Tracker.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PkrTFTum8cirDe8N90FSCp6kIjh2BQe-

Install Dependencies
"""

pip install pandas numpy scikit-learn matplotlib seaborn streamlit statsmodels

import pandas as pd
import numpy as np
import pickle
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder

df = pd.read_csv("/content/finance_data_large.csv")  # Ensure columns: Date, Amount, Description, Category

df

df.shape

df.describe()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Convert Date column to datetime format
df["Date"] = pd.to_datetime(df["Date"])

# Aggregate total spending per category
category_spending = df.groupby("Category")["Amount"].sum().sort_values(ascending=False)

# Aggregate monthly spending
df["Month"] = df["Date"].dt.to_period("M")
monthly_spending = df.groupby("Month")["Amount"].sum()

"""Performing Visualizations"""

# Plot 1: Spending per Category (Bar Chart)
plt.figure(figsize=(12, 6))
sns.barplot(x=category_spending.index, y=category_spending.values, palette="viridis")
plt.xticks(rotation=45)
plt.xlabel("Category")
plt.ylabel("Total Spending (₹)")
plt.title("Total Spending by Category")
plt.show()

# Plot 2: Monthly Spending Trend (Line Chart)
plt.figure(figsize=(12, 6))
sns.lineplot(x=monthly_spending.index.astype(str), y=monthly_spending.values, marker="o", color="b")
plt.xticks(rotation=45)
plt.xlabel("Month")
plt.ylabel("Total Spending (₹)")
plt.title("Monthly Spending Trend")
plt.grid(True)
plt.show()

# Plot 3: Distribution of Transaction Amounts (Histogram)
plt.figure(figsize=(12, 6))
sns.histplot(df["Amount"], bins=30, kde=True, color="r")
plt.xlabel("Transaction Amount (₹)")
plt.ylabel("Frequency")
plt.title("Distribution of Transaction Amounts")
plt.show()

# Boxplot: Distribution of Spending Across Categories
plt.figure(figsize=(12, 6))
sns.boxplot(x="Category", y="Amount", data=df, palette="coolwarm")
plt.xticks(rotation=45)
plt.xlabel("Category")
plt.ylabel("Transaction Amount (₹)")
plt.title("Boxplot of Spending Across Categories")
plt.show()

"""Normalising the data"""

le = LabelEncoder()
df['Category'] = le.fit_transform(df['Category'])

"""Feature Selection"""

# Features and Target
X = df[['Amount']]
y = df['Category']

# Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

"""Random Forest Model (Expense Categorization)"""

# Train Random Forest Model
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)

# Save Model
with open("rf_model.pkl", "wb") as f:
    pickle.dump(rf_model, f)

# Save Label Encoder
with open("label_encoder.pkl", "wb") as f:
    pickle.dump(le, f)

print("Random Forest Model Saved!")

# Predict on test data
y_pred = rf_model.predict(X_test)

# Import accuracy_score, classification_report, and confusion_matrix
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Evaluate the accuracy of the model
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy * 100:.2f}%')

# Additional Metrics
print("Classification Report:")
print(classification_report(y_test, y_pred))

# Confusion Matrix
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

"""Train Time Series Model (Budget Forecasting)"""

import pandas as pd
import pickle
import statsmodels.api as sm

# Load Data
df = pd.read_csv("/content/finance_data_large.csv")  # Ensure columns: Date, Amount
df['Date'] = pd.to_datetime(df['Date'])
df.set_index('Date', inplace=True)

# Aggregate monthly expenses
df_monthly = df.resample('M').sum()

# Train ARIMA Model
model = sm.tsa.ARIMA(df_monthly['Amount'], order=(2,1,2))
model_fit = model.fit()

# Save Model
with open("forecast_model.pkl", "wb") as f:
    pickle.dump(model_fit, f)

print("Time Series Model Saved!")

# Let's assume you have actual future values to compare with forecast (e.g., next 12 months actual data)
# Actual future data (for example purposes, this would be the true values of the next 12 months)
actual_values = [35000, 38000, 39000, 36000, 34000, 33000, 31000, 30000, 28000, 27000, 26000, 25000]

# Evaluate using MAE, MSE, RMSE, and R²
mae = mean_absolute_error(actual_values, forecast)
mse = mean_squared_error(actual_values, forecast)
rmse = np.sqrt(mse)
r2 = r2_score(actual_values, forecast)

print(f"Mean Absolute Error (MAE): {mae}")
print(f"Mean Squared Error (MSE): {mse}")
print(f"Root Mean Squared Error (RMSE): {rmse}")
print(f"R² Score: {r2}")

# Install pmdarima if needed
!pip install pmdarima

from pmdarima import auto_arima

# Auto ARIMA to find the best p, d, q
auto_model = auto_arima(df_monthly['Amount'], seasonal=False, stepwise=True, trace=True)

# Summarize the best model
auto_model.summary()

"""Build a Streamlit Dashboard"""

import streamlit as st
import pandas as pd
import numpy as np
import pickle
from datetime import datetime

# Load Models
with open("rf_model.pkl", "rb") as f:
    rf_model = pickle.load(f)

with open("label_encoder.pkl", "rb") as f:
    label_encoder = pickle.load(f)

with open("forecast_model.pkl", "rb") as f:
    forecast_model = pickle.load(f)

# Streamlit UI
st.title("💰 Personalized Finance Tracker")
st.subheader("Track Expenses & Predict Future Budget")

# User Input for Expense Categorization
st.header("📊 Expense Categorization")
amount = st.number_input("Enter Expense Amount", min_value=0.0, step=100.0)
if st.button("Categorize Expense"):
    category_index = rf_model.predict([[amount]])[0]
    category_name = label_encoder.inverse_transform([category_index])[0]
    st.success(f"Predicted Category: {category_name}")

# User Input for Budget Forecasting
st.header("📈 Budget Forecasting")
months = st.slider("Select Months to Forecast", 1, 12, 3)

if st.button("Predict Future Expenses"):
    forecast = forecast_model.forecast(steps=months)
    for i, value in enumerate(forecast):
        st.write(f"Month {i+1}: ₹{value:.2f}")

plt.figure(figsize=(10, 5))
sns.lineplot(data=df_monthly, x=df_monthly.index, y='Amount', marker='o')
plt.title("📈 Expense Trend Over Time")
plt.xlabel("Date")
plt.ylabel("Total Expenses")
plt.grid(True)
plt.show()

# STEP 7: Predict Future Budget (Next 3 Months)
forecast = model_fit.forecast(steps=3)
print("\n Budget Forecast for Next 3 Months:")
for i, value in enumerate(forecast):
    print(f"Month {i+1}: ₹{value:.2f}")

!pip install streamlit

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# st.title("Finance Tracker")
#

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# 
# # Simple Streamlit App
# st.title("Personalized Finance Tracker")
# st.write("Welcome to your finance tracker app! You can visualize and analyze your spending habits here.")
#

!pip install pyngrok

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from statsmodels.tsa.arima.model import ARIMA
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report
from pmdarima import auto_arima

# Set page title
st.title("Personalized Finance Tracker")

# File uploader
uploaded_file = st.file_uploader("/content/finance_data_large.csv", type=["csv"])

if uploaded_file is not None:
    df = pd.read_csv(uploaded_file)
    df['Date'] = pd.to_datetime(df['Date'])
    df.set_index('Date', inplace=True)

    st.write("###Preview of Data")
    st.dataframe(df.head())

    # ---- Data Preprocessing ----
    # Handling missing values
    df = df.fillna(method='ffill')

    # ---- Time-Series Forecasting (ARIMA) ----
    st.subheader("ARIMA Forecasting (Future Expense Prediction)")

    # Resampling data to monthly frequency
    df_monthly = df.resample('M').sum()

    # Auto ARIMA to find best model parameters
    auto_model = auto_arima(df_monthly['Amount'], seasonal=False, stepwise=True, trace=False)
    best_p, best_d, best_q = auto_model.order

    # Fit ARIMA Model
    model = ARIMA(df_monthly['Amount'], order=(best_p, best_d, best_q))
    model_fit = model.fit()

    # Forecast for the next 12 months
    forecast_steps = 12
    forecast = model_fit.forecast(steps=forecast_steps)
    forecast_dates = pd.date_range(df_monthly.index[-1], periods=forecast_steps + 1, freq='M')[1:]

    # Show Forecast
    forecast_df = pd.DataFrame(forecast, index=forecast_dates, columns=['Forecast'])
    st.write("### Forecast for Next 12 Months:")
    st.dataframe(forecast_df)

    # Plot actual vs forecasted spending
    plt.figure(figsize=(12, 6))
    plt.plot(df_monthly.index, df_monthly['Amount'], label="Actual Data", color='blue')
    plt.plot(forecast_df.index, forecast_df['Forecast'], label="Forecast", color='red')
    plt.xlabel("Date")
    plt.ylabel("Amount Spent (₹)")
    plt.title("Expense Forecasting with ARIMA")
    plt.legend()
    st.pyplot(plt)

    # ---- Transaction Classification (Random Forest) ----
    st.subheader("Transaction Classification with Random Forest")

    # Check if Category column exists
    if "Category" in df.columns:
        X = df[['Amount']]  # Feature
        y = df['Category']  # Target variable

        # Splitting the dataset
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

        # Train Random Forest Model
        rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
        rf_model.fit(X_train, y_train)

        # Predictions
        y_pred = rf_model.predict(X_test)

        # Accuracy
        accuracy = accuracy_score(y_test, y_pred)
        st.write(f"**🔹 Model Accuracy: {accuracy * 100:.2f}%**")

        # Classification Report
        st.write("### Classification Report")
        st.text(classification_report(y_test, y_pred))

        # User Input for Prediction
        st.write("### Predict Transaction Category")
        amount_input = st.number_input("Enter transaction amount:", min_value=0)
        if st.button("Predict Category"):
            category_pred = rf_model.predict([[amount_input]])
            st.write(f"**Predicted Category:** {category_pred[0]}")

    else:
        st.write("Please ensure your dataset contains a 'Category' column for transaction classification.")

